### ISSUE TITLE
Running yowsup-queue crashes

### ISSUE THREAD

**Issue by jeanlinux** [EliasKotlyar/yowsup-queue#1]
I am trying to run yowsup-queue and i an running into some problems, unfortuantely for me i cant figure out why or whats wrong at the moment, dont know python, here is the stack trace from the error

Traceback (most recent call last):
  File "run.py", line 14, in <module>
    stack.start(config)
  File "/Users/jeanlinux/projects/tools/yowsup-queue/yowsupqueue/stack.py", line 35, in start
    .pushDefaultLayers(True) \
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/yowsup/stacks/yowstack.py", line 51, in pushDefaultLayers
    defaultLayers = YowStackBuilder.getDefaultLayers(axolotl)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/yowsup/stacks/yowstack.py", line 73, in getDefaultLayers
    from yowsup.layers.axolotl import YowAxolotlLayer
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/yowsup/layers/axolotl/**init**.py", line 1, in <module>
    from .layer import YowAxolotlLayer
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/yowsup/layers/axolotl/layer.py", line 3, in <module>
    from axolotl.util.keyhelper import KeyHelper
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/axolotl/util/keyhelper.py", line 3, in <module>
    from ..identitykeypair import IdentityKeyPair
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/axolotl/identitykeypair.py", line 1, in <module>
    from .state.storageprotos import IdentityKeyPairStructure
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/axolotl/state/storageprotos.py", line 8, in <module>
    from google.protobuf import reflection as _reflection
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/google/protobuf/reflection.py", line 68, in <module>
    from google.protobuf.internal import python_message
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/google/protobuf/internal/python_message.py", line 848
    except struct.error, e:
                       ^
SyntaxError: invalid syntax

**Comment by EliasKotlyar** [comment]
Hello Jean,

It seems thats an error in the python_message.py which belongs to the protobuf package.
I googled it up,and this error has been seen in another context.

http://stackoverflow.com/questions/29389754/how-do-we-use-python-generated-protobuf-codes-in-to-python-code

To fix this bug,consider updating this library.
