### ISSUE TITLE
Syntax error in python_message.py

### ISSUE THREAD

**Issue by axpence** [EliasKotlyar/yowsup-queue#2]
I have been trying to install yowsup-queue and when trying to run the run.py script via the following command: `root@SUP:~/yowsup-queue# python3 run.py` I am getting a syntax error within the `/usr/local/lib/python3.4/dist-packages/google/protobuf/internal/python_message.py` file (see below for details).

root@SUP:~/yowsup-queue# python3 run.py
Traceback (most recent call last):
  File "run.py", line 14, in <module>
    stack.start(config)
  File "/root/yowsup-queue/yowsupqueue/stack.py", line 37, in start
    .build()
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4-py3.4.egg/yowsup/stacks/yowstack.py", line 51, in pushDefaultLayers
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4-py3.4.egg/yowsup/stacks/yowstack.py", line 73, in getDefaultLayers
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4-py3.4.egg/yowsup/layers/axolotl/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4-py3.4.egg/yowsup/layers/axolotl/layer.py", line 3, in <module>
  File "/usr/local/lib/python3.4/dist-packages/axolotl/util/keyhelper.py", line 3, in <module>
    from ..identitykeypair import IdentityKeyPair
  File "/usr/local/lib/python3.4/dist-packages/axolotl/identitykeypair.py", line 1, in <module>
    from .state.storageprotos import IdentityKeyPairStructure
  File "/usr/local/lib/python3.4/dist-packages/axolotl/state/storageprotos.py", line 8, in <module>
    from google.protobuf import reflection as _reflection
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/reflection.py", line 68, in <module>
    from google.protobuf.internal import python_message
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/internal/python_message.py", line 848
    except struct.error, e:
                       ^
SyntaxError: invalid syntax

**Comment by axpence** [comment]
Try fixing via the following command:

     pip3 install -Iv protobuf==3.0.0-alpha-1

this upgrades to protobuf >=2.6

**Comment by axpence** [comment]
the above fixed this issue.
