### ISSUE TITLE
ConnectionRefusedError when running "python3 run.py" command.

### ISSUE THREAD

**Issue by axpence** [EliasKotlyar/yowsup-queue#3]
I am getting a `ConnectionRefusedError` when running `python3 run.py`command.
I am confused because when I send a test message to the phone number it properly displays the message. I think Beanstalkd may be an issue? I installed as per the Readme.

root@SUP:~/yowsup-queue# python3 run.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pystalkd/Beanstalkd.py", line 51, in wrap
    return wrapped_function(_args, *_kwargs)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/root/yowsup-queue/yowsupqueue/beanstalkstack.py", line 21, in run
    self.beanstalk = Connection(host=self.host, port=int(self.port))
  File "/usr/local/lib/python3.4/dist-packages/pystalkd/Beanstalkd.py", line 86, in __init__
    self.connect()
  File "/usr/local/lib/python3.4/dist-packages/pystalkd/Beanstalkd.py", line 93, in connect
    SocketError.wrap(self._socket.connect, (self.host, self.port))
  File "/usr/local/lib/python3.4/dist-packages/pystalkd/Beanstalkd.py", line 53, in wrap
    raise SocketError(err)
pystalkd.Beanstalkd.SocketError: [Errno 111] Connection refused

Sucessfully Connected..
We've already setup a session for this V3 message, letting bundled message fall through...
Received Message from 18871234567@s.whatsapp.net : This is a TEST MESSAGE HELLLLOOOOO

**Comment by EliasKotlyar** [comment]
Hello,

i suppose that the Error is
" pystalkd.Beanstalkd.SocketError: [Errno 111] Connection refused"

Please try to check the Connection to the Beanstalkd Server

PS: I am using the following Software for testing Beanstalkd Queus:
https://github.com/ptrofimov/beanstalk_console
