### ISSUE TITLE
Crashes when someone sends emoji

### ISSUE THREAD

**Issue by spkprav** [EliasKotlyar/yowsup-queue#6]
Hi, I have trying to integrate this with ruby.
I tried sending an emoji and the yowsup-queue crashes, I have to restart the app again.
Please help.

**Comment by EliasKotlyar** [comment]
Hello 

Can you please provide additional Information (like a crash-log)? I tryed myself with emojis today,and it was running fine.

Greetings
Elias

**Comment by spkprav** [comment]
Hi, Sorry for not providing stack trace.
I tried solving this issue by adding `encode('unicode_escape')` in "yowsup-queue/yowsupqueue/layer.py", line 214
```
Traceback (most recent call last):
  File "run.py", line 14, in <module>
    stack.start(config)
  File "/home/ubuntu/www/yowsup-queue/yowsupqueue/stack.py", line 55, in start
    self.stack.loop(timeout = 0.5)
  File "/usr/local/lib/python3.4/dist-packages/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python3.4/asyncore.py", line 208, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python3.4/asyncore.py", line 153, in poll
    read(obj)
  File "/usr/lib/python3.4/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python3.4/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.4/asyncore.py", line 442, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python3.4/dist-packages/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/usr/local/lib/python3.4/dist-packages/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.4/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.4/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/usr/local/lib/python3.4/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python3.4/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.4/dist-packages/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python3.4/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.4/dist-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python3.4/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.4/dist-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.4/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.4/dist-packages/yowsup/layers/axolotl/layer.py", line 117, in receive
    self.onMessage(protocolTreeNode)
  File "/usr/local/lib/python3.4/dist-packages/yowsup/layers/axolotl/layer.py", line 141, in onMessage
    self.toUpper(protocolTreeNode)
  File "/usr/local/lib/python3.4/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.4/dist-packages/yowsup/layers/__init__.py", line 169, in receive
    s.receive(data)
  File "/usr/local/lib/python3.4/dist-packages/yowsup/layers/__init__.py", line 105, in receive
    recv(node)
  File "/usr/local/lib/python3.4/dist-packages/yowsup/layers/protocol_messages/layer.py", line 21, in recvMessageStanza
    self.toUpper(entity) 
  File "/usr/local/lib/python3.4/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.4/dist-packages/yowsup/layers/interface/interface.py", line 98, in receive
    self.callbacks[entityType](entity)
  File "/home/ubuntu/www/yowsup-queue/yowsupqueue/layer.py", line 93, in onMessage
    self.output("Received Message from %s : %s" % (messageProtocolEntity.getFrom(), messageBody))
  File "/home/ubuntu/www/yowsup-queue/yowsupqueue/layer.py", line 214, in output
    print(str)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 53-56: ordinal not in range(128)
```

**Comment by EliasKotlyar** [comment]
Hello 

Many Thanks for this Log. Can you please provide a description how i can reproduce this error? I suppose you are sending a special emoji,which cannot be handled. Also you can just comment this line,because its only for debugging purposes.

Greetings
Elias

**Comment by spkprav** [comment]
Hi, Sorry for the delay. I sent :speak_no_evil: emoji, but it happened for all emoji's.
Anyway, it's just a log, I commented it and it works fine now.

**Comment by abkheemskerk** [comment]
where and what did you comment out? i also have trouble with all the emojis and special characters like ë or à
